markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html 

#摘要分隔符，书写博文时使用
excerpt_separator: "<!-- more -->"

#站点信息，需要修改成自己的!!!
github: xianqincanglang
author: "xianqincanglang"
email: m15993343056@163.com
name: "TianZe's Blog"
baseurl: /
url: https://xianqincanglang.github.io
domain: xianqincanglang.github.io

#栏目配置，请根据博客需要，参照着自行规划!!!
#每个栏目包含三个信息：
#1.栏目标签（英文），每篇文章通过category字段指定
#2.栏目名称，为栏目标签对应的栏目名
#3.栏目列表链接，一般为”/栏目标签/index.html“即可
all_categories: [
  ["IOS", "iOS开发","/IOS/index.html"], 
  # ["react", "React Native", "/react/index.html"],
  # ["web", "Web建站","/web/index.html"], 
  # ["linux", "Linux相关","/linux/index.html"],
  ["Git", "Git用法","/Git/index.html"],
  # ["program", "软件开发","/program/index.html"],
  # ["vps", "VPS","/vps/index.html"],
  # ["other", "杂记","/other/index.html"],
  # ["read", "书摘","/read/index.html"], 
  ["Other", "其他","/Other/index.html"],
  ["about", "关于","/about.html"]
]

#分页配置
paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
#gems: [jekyll-paginate,jekyll-paginate-category]
plugins: [jekyll-paginate]

copyright: []
#timezone: Asia/Shanghai
